language: node_js

node_js:
  - "node"

script:  
  - npm install
  - npm run build
  - ls build/ -lh  

before_deploy:
  - cd build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: "cvmfundexplorer.conradoqg.eti.br"
  skip_cleanup: true
  region: "sa-east-1"
  on:
    condition: $TRAVIS_BRANCH = master